apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapi-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaikhxsn/argo-app.git
    targetRevision: HEAD
    path: my-api
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapi
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true