apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 1
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: saqlainshaikh/api:20250329080712
        ports:
        - containerPort: 5238
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: myapi-config
              key: ASPNETCORE_ENVIRONMENT