apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 2
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: saqlainshaikh/api:20250323111015
        ports:
        - containerPort: 5238
